### ISSUE TITLE
Business contact - Need to carry out a project using private maps

### ISSUE THREAD

**Issue by rafaelpoa** [znc15/msfs2020-map-enhancement-Chinese#4]
I would like to discuss a project; I'd like to create a MOD for the flight simulator that uses real-time images from a supplier like those provided by [www.planet.com](http://www.planet.com/). Are you interested in undertaking this project? Let's talk about a price for this development. Please contact me at [CONTATO@BRANDGAMING.COM.BR](mailto:CONTATO@BRANDGAMING.COM.BR).

Thank you, and I apologize for the way I had to send this message; I couldn't find your contact information.

**Comment by znc15** [comment]
I'm not the author of this software, I'm just in charge of translating it
